# Generated by zkapi-clientd/scripts/assemble-release.py from the exact release archives.
{ lib, stdenv, fetchurl, makeWrapper, autoPatchelfHook, openssl, cacert }:
let
  version = "0.1.2";
  archives = {
    x86_64-linux = { target = "linux_amd64"; sha256 = "11f8e24d7612a8bd28981194a5fa4999ae0cccbd50366364f14a8ce1e7d63497"; };
    aarch64-linux = { target = "linux_arm64"; sha256 = "89f719dceeed67d40a6da75ff6aae2eb51feae63724067ee5d6d569f3308e1c7"; };
    x86_64-darwin = { target = "darwin_amd64"; sha256 = "d02b5025b355149120e3c656dfe711f2444e540c33c9514320e9746d0fcb8bed"; };
    aarch64-darwin = { target = "darwin_arm64"; sha256 = "2bf4c25501d8a77ffc4d759b21e9ac4de739c0330fd163d707a1eb866daa2856"; };
  };
  archive = archives.${stdenv.hostPlatform.system} or
    (throw "zkapi-clientd binary releases do not support ${stdenv.hostPlatform.system}");
in
stdenv.mkDerivation {
  pname = "zkapi-clientd";
  inherit version;
  src = fetchurl {
    url = "https://github.com/OpenAnonymity/zkapi/releases/download/clientd-v0.1.2/zkapi-clientd_${version}_${archive.target}.tar.gz";
    inherit (archive) sha256;
  };

  # Native archives have their payload at the top level, without a source root.
  sourceRoot = ".";
  dontConfigure = true;
  dontBuild = true;
  dontStrip = true;
  nativeBuildInputs = [ makeWrapper ] ++ lib.optionals stdenv.hostPlatform.isLinux [ autoPatchelfHook ];
  buildInputs = lib.optionals stdenv.hostPlatform.isLinux [ openssl stdenv.cc.cc.lib ];

  installPhase = ''
    runHook preInstall
    install -Dm755 zkapi-clientd "$out/bin/zkapi-clientd"
    install -Dm755 zkapi-walletd "$out/bin/zkapi-walletd"
    mkdir -p "$out/share/doc/zkapi-clientd" "$out/share/licenses/zkapi-clientd"
    cp -R share/zkapi-clientd "$out/share/zkapi-clientd"
    install -m644 CLI_PACKAGING.md "$out/share/doc/zkapi-clientd/CLI_PACKAGING.md"
    install -m644 LICENSE "$out/share/licenses/zkapi-clientd/LICENSE"
    install -m644 VERSION "$out/share/zkapi-clientd/VERSION"
    ${lib.optionalString stdenv.hostPlatform.isLinux ''
      install -Dm644 zkapi-clientd.service "$out/lib/systemd/user/zkapi-clientd.service"
      substituteInPlace "$out/lib/systemd/user/zkapi-clientd.service" \
        --replace-fail /usr/bin/zkapi-clientd "$out/bin/zkapi-clientd"
    ''}
    # The bundled companion wins over an unrelated executable in the user's PATH.
    # Keep zkapi-walletd unwrapped: its resolved ../share directory locates the proof keys.
    wrapProgram "$out/bin/zkapi-clientd" \
      --prefix PATH : "$out/bin" \
      --set-default SSL_CERT_FILE "${cacert}/etc/ssl/certs/ca-bundle.crt"
    runHook postInstall
  '';

  doInstallCheck = true;
  installCheckPhase = ''
    runHook preInstallCheck
    test "$("$out/bin/zkapi-clientd" version)" = "zkapi-clientd ${version}"
    "$out/bin/zkapi-walletd" --help >/dev/null
    for asset in request.pk request.vk withdrawal.pk withdrawal.vk manifest.json; do
      test -s "$out/share/zkapi-clientd/proof-setup/$asset"
    done
    runHook postInstallCheck
  '';

  meta = {
    description = "Local inference API with private prepaid zkAPI access";
    homepage = "https://github.com/OpenAnonymity/zkapi";
    license = lib.licenses.mit;
    mainProgram = "zkapi-clientd";
    platforms = builtins.attrNames archives;
    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];
  };
}
