# Generated by zkapi-clientd/scripts/assemble-release.py from the exact release archives.
{ lib, stdenv, fetchurl, makeWrapper, autoPatchelfHook, openssl, cacert }:
let
  version = "0.1.5";
  archives = {
    x86_64-linux = { target = "linux_amd64"; sha256 = "be52cffaa22daa7a410ad23b15fdf23fa3e92f203457939de9ccaec2b7e809d3"; };
    aarch64-linux = { target = "linux_arm64"; sha256 = "6f2c11a2168387ec8ae64f037f53cdc082969bf6e749652ed4b5c0d06ae9a062"; };
    x86_64-darwin = { target = "darwin_amd64"; sha256 = "b1627d6a13de16b19fc5023a99ae77ff65a0da009305b13be55189169f5f4f29"; };
    aarch64-darwin = { target = "darwin_arm64"; sha256 = "19b5ab7c2485fcb31809990ab42469b751d2530dda77036b4ca4e61eee09ccaa"; };
  };
  archive = archives.${stdenv.hostPlatform.system} or
    (throw "zkapi-clientd binary releases do not support ${stdenv.hostPlatform.system}");
in
stdenv.mkDerivation {
  pname = "zkapi-clientd";
  inherit version;
  src = fetchurl {
    url = "https://github.com/ethereum/zkapi/releases/download/clientd-v0.1.5/zkapi-clientd_${version}_${archive.target}.tar.gz";
    inherit (archive) sha256;
  };

  # Native archives have their payload at the top level, without a source root.
  sourceRoot = ".";
  dontConfigure = true;
  dontBuild = true;
  dontStrip = true;
  nativeBuildInputs = [ makeWrapper ] ++ lib.optionals stdenv.hostPlatform.isLinux [ autoPatchelfHook ];
  buildInputs = lib.optionals stdenv.hostPlatform.isLinux [ openssl stdenv.cc.cc.lib ];

  installPhase = ''
    runHook preInstall
    install -Dm755 zkapi-clientd "$out/bin/zkapi-clientd"
    install -Dm755 zkapi-walletd "$out/bin/zkapi-walletd"
    mkdir -p "$out/share/doc/zkapi-clientd" "$out/share/licenses/zkapi-clientd"
    cp -R share/zkapi-clientd "$out/share/zkapi-clientd"
    install -m644 CLI_PACKAGING.md "$out/share/doc/zkapi-clientd/CLI_PACKAGING.md"
    install -m644 LICENSE "$out/share/licenses/zkapi-clientd/LICENSE"
    install -m644 VERSION "$out/share/zkapi-clientd/VERSION"
    ${lib.optionalString stdenv.hostPlatform.isLinux ''
      install -Dm644 zkapi-clientd.service "$out/lib/systemd/user/zkapi-clientd.service"
      substituteInPlace "$out/lib/systemd/user/zkapi-clientd.service" \
        --replace-fail /usr/bin/zkapi-clientd "$out/bin/zkapi-clientd"
    ''}
    # The bundled companion wins over an unrelated executable in the user's PATH.
    # Keep zkapi-walletd unwrapped: its resolved ../share directory locates the proof keys.
    wrapProgram "$out/bin/zkapi-clientd" \
      --prefix PATH : "$out/bin" \
      --set-default SSL_CERT_FILE "${cacert}/etc/ssl/certs/ca-bundle.crt"
    runHook postInstall
  '';

  doInstallCheck = true;
  installCheckPhase = ''
    runHook preInstallCheck
    test "$("$out/bin/zkapi-clientd" version)" = "zkapi-clientd ${version}"
    "$out/bin/zkapi-walletd" --help >/dev/null
    for asset in request.pk request.vk withdrawal.pk withdrawal.vk manifest.json; do
      test -s "$out/share/zkapi-clientd/proof-setup/$asset"
    done
    runHook postInstallCheck
  '';

  meta = {
    description = "Local inference API with private prepaid zkAPI access";
    homepage = "https://github.com/ethereum/zkapi";
    license = lib.licenses.mit;
    mainProgram = "zkapi-clientd";
    platforms = builtins.attrNames archives;
    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];
  };
}
