# Generated by zkapi-clientd/scripts/assemble-release.py; do not edit checksums manually.
class ZkapiClientd < Formula
  desc "Local inference API with private prepaid zkAPI access"
  homepage "https://github.com/ethereum/zkapi"
  version "0.1.4"
  license "MIT"

  on_macos do
    depends_on macos: :ventura
    on_arm do
      url "https://github.com/ethereum/zkapi/releases/download/clientd-v0.1.4/zkapi-clientd_0.1.4_darwin_arm64.tar.gz"
      sha256 "049cd6bccd55d5d6cdf139b29ba17aaf654a15b7a0a6bb814d7d36fdb5611299"
    end
    on_intel do
      url "https://github.com/ethereum/zkapi/releases/download/clientd-v0.1.4/zkapi-clientd_0.1.4_darwin_amd64.tar.gz"
      sha256 "750f9a4dcc438e9c365f96da5eaf8968718ffb071a9bf0f77eb00f2d141d6de5"
    end
  end

  on_linux do
    depends_on "openssl@3"
    depends_on "patchelf" => :build
    on_arm do
      url "https://github.com/ethereum/zkapi/releases/download/clientd-v0.1.4/zkapi-clientd_0.1.4_linux_arm64.tar.gz"
      sha256 "49691d6559a93c75010eb953a5368cd48084bfb91a8175f0f307b2935aed5436"
    end
    on_intel do
      url "https://github.com/ethereum/zkapi/releases/download/clientd-v0.1.4/zkapi-clientd_0.1.4_linux_amd64.tar.gz"
      sha256 "c037d938e12239393b121384fe19514c7f4d141f40bdcc02ec38c0504dac273e"
    end
  end

  def install
    bin.install "zkapi-clientd", "zkapi-walletd"
    (share/"doc/zkapi-clientd").install "CLI_PACKAGING.md"
    prefix.install "LICENSE"
    share.install "share/zkapi-clientd"

    # Release ELF binaries use OpenSSL's SONAME; brewed libraries are keg-only.
    # Put the managed dependency in RUNPATH so services need no loader variables.
    if OS.linux?
      system Formula["patchelf"].opt_bin/"patchelf", "--add-rpath",
             Formula["openssl@3"].opt_lib, bin/"zkapi-walletd"
    end
  end

  service do
    run [opt_bin/"zkapi-clientd", "serve"]
    keep_alive true
    environment_variables PATH: std_service_path_env
    log_path var/"log/zkapi-clientd.log"
    error_log_path var/"log/zkapi-clientd.log"
    restart_delay 5
    throttle_interval 5
    stop_timeout 30
  end

  def caveats
    <<~EOS
      Initialize your private configuration before starting the service:
        zkapi-clientd config
        brew services start zkapi-clientd
      Run these commands as your own user. Each user has a separate wallet.
      Client API base URL: http://127.0.0.1:8787/v1
    EOS
  end

  test do
    assert_match "zkapi-clientd #{version}", shell_output("#{bin}/zkapi-clientd version")
    assert_match "Usage:", shell_output("#{bin}/zkapi-walletd --help")
    %w[request.pk request.vk withdrawal.pk withdrawal.vk manifest.json].each do |asset|
      assert_predicate share/"zkapi-clientd/proof-setup"/asset, :file?
      assert_operator (share/"zkapi-clientd/proof-setup"/asset).size, :>, 0
    end
    # Exercise the installed daemon without creating or funding a wallet.
    config = testpath/"private-config"
    assert_match "Run zkapi-clientd config",
                 shell_output("#{bin}/zkapi-clientd --config-dir #{config} serve 2>&1", 1)
    refute_path_exists config/"config.json"
  end
end
