# Generated by zkapi-clientd/scripts/assemble-release.py; do not edit checksums manually.
class ZkapiClientd < Formula
  desc "Local inference API with private prepaid zkAPI access"
  homepage "https://github.com/ethereum/zkapi"
  version "0.1.3"
  license "MIT"

  on_macos do
    depends_on macos: :ventura
    on_arm do
      url "https://github.com/ethereum/zkapi/releases/download/clientd-v0.1.3/zkapi-clientd_0.1.3_darwin_arm64.tar.gz"
      sha256 "7f7d1188f35f211b210563094c6354a1a3109f6318790ed89d32c45546bd5822"
    end
    on_intel do
      url "https://github.com/ethereum/zkapi/releases/download/clientd-v0.1.3/zkapi-clientd_0.1.3_darwin_amd64.tar.gz"
      sha256 "cde13c1021859cf0486ddce25ee9276791c953ff301794c5f629fba97228e95d"
    end
  end

  on_linux do
    depends_on "openssl@3"
    depends_on "patchelf" => :build
    on_arm do
      url "https://github.com/ethereum/zkapi/releases/download/clientd-v0.1.3/zkapi-clientd_0.1.3_linux_arm64.tar.gz"
      sha256 "1eb8b36618341aa406f6b83b2843c30dbadd5ad08dc86111f94961594b5bc26b"
    end
    on_intel do
      url "https://github.com/ethereum/zkapi/releases/download/clientd-v0.1.3/zkapi-clientd_0.1.3_linux_amd64.tar.gz"
      sha256 "fa9184770e7864cd71ac8081545a4e55036924dbae456632244682b8541addf5"
    end
  end

  def install
    bin.install "zkapi-clientd", "zkapi-walletd"
    (share/"doc/zkapi-clientd").install "CLI_PACKAGING.md"
    prefix.install "LICENSE"
    share.install "share/zkapi-clientd"

    # Release ELF binaries use OpenSSL's SONAME; brewed libraries are keg-only.
    # Put the managed dependency in RUNPATH so services need no loader variables.
    if OS.linux?
      system Formula["patchelf"].opt_bin/"patchelf", "--add-rpath",
             Formula["openssl@3"].opt_lib, bin/"zkapi-walletd"
    end
  end

  service do
    run [opt_bin/"zkapi-clientd", "serve"]
    keep_alive true
    environment_variables PATH: std_service_path_env
    log_path var/"log/zkapi-clientd.log"
    error_log_path var/"log/zkapi-clientd.log"
    restart_delay 5
    throttle_interval 5
    stop_timeout 30
  end

  def caveats
    <<~EOS
      Initialize your private configuration before starting the service:
        zkapi-clientd config
        brew services start zkapi-clientd
      Run these commands as your own user. Each user has a separate wallet.
      Client API base URL: http://127.0.0.1:8787/v1
    EOS
  end

  test do
    assert_match "zkapi-clientd #{version}", shell_output("#{bin}/zkapi-clientd version")
    assert_match "Usage:", shell_output("#{bin}/zkapi-walletd --help")
    %w[request.pk request.vk withdrawal.pk withdrawal.vk manifest.json].each do |asset|
      assert_predicate share/"zkapi-clientd/proof-setup"/asset, :file?
      assert_operator (share/"zkapi-clientd/proof-setup"/asset).size, :>, 0
    end
    # Exercise the installed daemon without creating or funding a wallet.
    config = testpath/"private-config"
    assert_match "Run zkapi-clientd config",
                 shell_output("#{bin}/zkapi-clientd --config-dir #{config} serve 2>&1", 1)
    refute_path_exists config/"config.json"
  end
end
