# Generated by zkapi-clientd/scripts/assemble-release.py; do not edit checksums manually.
class ZkapiClientd < Formula
  desc "Local inference API with private prepaid zkAPI access"
  homepage "https://github.com/ethereum/zkapi"
  version "0.1.5"
  license "MIT"

  on_macos do
    depends_on macos: :ventura
    on_arm do
      url "https://github.com/ethereum/zkapi/releases/download/clientd-v0.1.5/zkapi-clientd_0.1.5_darwin_arm64.tar.gz"
      sha256 "19b5ab7c2485fcb31809990ab42469b751d2530dda77036b4ca4e61eee09ccaa"
    end
    on_intel do
      url "https://github.com/ethereum/zkapi/releases/download/clientd-v0.1.5/zkapi-clientd_0.1.5_darwin_amd64.tar.gz"
      sha256 "b1627d6a13de16b19fc5023a99ae77ff65a0da009305b13be55189169f5f4f29"
    end
  end

  on_linux do
    depends_on "openssl@3"
    depends_on "patchelf" => :build
    on_arm do
      url "https://github.com/ethereum/zkapi/releases/download/clientd-v0.1.5/zkapi-clientd_0.1.5_linux_arm64.tar.gz"
      sha256 "6f2c11a2168387ec8ae64f037f53cdc082969bf6e749652ed4b5c0d06ae9a062"
    end
    on_intel do
      url "https://github.com/ethereum/zkapi/releases/download/clientd-v0.1.5/zkapi-clientd_0.1.5_linux_amd64.tar.gz"
      sha256 "be52cffaa22daa7a410ad23b15fdf23fa3e92f203457939de9ccaec2b7e809d3"
    end
  end

  def install
    bin.install "zkapi-clientd", "zkapi-walletd"
    (share/"doc/zkapi-clientd").install "CLI_PACKAGING.md"
    prefix.install "LICENSE"
    share.install "share/zkapi-clientd"

    # Release ELF binaries use OpenSSL's SONAME; brewed libraries are keg-only.
    # Put the managed dependency in RUNPATH so services need no loader variables.
    if OS.linux?
      system Formula["patchelf"].opt_bin/"patchelf", "--add-rpath",
             Formula["openssl@3"].opt_lib, bin/"zkapi-walletd"
    end
  end

  service do
    run [opt_bin/"zkapi-clientd", "serve"]
    keep_alive true
    environment_variables PATH: std_service_path_env
    log_path var/"log/zkapi-clientd.log"
    error_log_path var/"log/zkapi-clientd.log"
    restart_delay 5
    throttle_interval 5
    stop_timeout 30
  end

  def caveats
    <<~EOS
      Initialize your private configuration before starting the service:
        zkapi-clientd config
        brew services start zkapi-clientd
      Run these commands as your own user. Each user has a separate wallet.
      Client API base URL: http://127.0.0.1:8787/v1
    EOS
  end

  test do
    assert_match "zkapi-clientd #{version}", shell_output("#{bin}/zkapi-clientd version")
    assert_match "Usage:", shell_output("#{bin}/zkapi-walletd --help")
    %w[request.pk request.vk withdrawal.pk withdrawal.vk manifest.json].each do |asset|
      assert_predicate share/"zkapi-clientd/proof-setup"/asset, :file?
      assert_operator (share/"zkapi-clientd/proof-setup"/asset).size, :>, 0
    end
    # Exercise the installed daemon without creating or funding a wallet.
    config = testpath/"private-config"
    assert_match "Run zkapi-clientd config",
                 shell_output("#{bin}/zkapi-clientd --config-dir #{config} serve 2>&1", 1)
    refute_path_exists config/"config.json"
  end
end
